exec(open('/private/tmp/xweb-next-references/check-pages.py').read().split('for name in sys.argv[1:]:')[0])
results=[{'page':p,'width':w,'status':'pass','evidence':'completed prior journey in browser-trace.jsonl and per-state artifacts; preserved across QA resume'} for p,w in [('pixel-world',1440),('buzzkit',1440),('horizonx',1440),('pixel-world',375)]]
def visit(name,width):
 run('set','viewport',str(width),'1000' if width==1440 else '812');snap()
 run('set','media','light');snap()
 run('open','http://localhost:4173/'+name+'/');snap();run('webmcp','list')
 run('wait','--load','networkidle');snap()
def assert_js(code):assert js(code),code
def audit(label,selector):
 data=json.loads(run('a11y','--selector',selector,'--json'))
 (O/f'{label}-a11y.json').write_text(json.dumps(data,indent=2))
 assert not data['data']['violations'],[(v['id'],v['nodeCount']) for v in data['data']['violations']]
for width in [375]:
 if False:
  visit('pixel-world',width)
  run('find','role','link','click','--name','Say hello');snap()
  assert_js('document.querySelector("#contact").open')
  run('click','button[type=submit]');snap()
  assert_js('!document.querySelector("form").checkValidity()')
  run('fill','input[name=name]','   ');snap();run('fill','input[name=email]','qa@example.com');snap();run('fill','textarea','   ');snap();run('click','button[type=submit]');snap()
  assert_js('!document.querySelector("input[name=name]").checkValidity()')
  run('screenshot',str(O/f'pixel-contact-{width}-invalid.png'))
  run('fill','input[name=name]','Template QA');snap();run('fill','input[name=email]','bad-email');snap();run('fill','textarea','A useful project idea.');snap();run('click','button[type=submit]');snap()
  assert_js('!document.querySelector("input[name=email]").checkValidity()')
  run('fill','input[name=email]','qa@example.com');snap()
  message=('A thoughtful product with a practical purpose. '*40)[:1500]
  run('fill','textarea',message);snap()
  download=O/f'pixel-contact-{width}.txt';run('download','button[type=submit]',str(download));snap()
  assert download.read_text()==f'From: Template QA <qa@example.com>\n\n{message.strip()}\n'
  assert_js('document.querySelector("#draft-status").textContent.includes("Nothing was sent")')
  assert_js('document.documentElement.scrollWidth===innerWidth')
  audit(f'pixel-contact-{width}','#contact')
  run('screenshot',str(O/f'pixel-contact-{width}-success.png'))
  run('press','Escape');snap()
  assert_js('!document.querySelector("#contact").open && document.activeElement.hasAttribute("data-contact")')
  run('find','role','link','click','--name','Say hello');snap()
  js('URL.createObjectURL = () => {throw new Error("QA download denied")};true');snap();run('click','button[type=submit]');snap()
  assert_js('document.querySelector("#draft-status").textContent.includes("Could not create") && document.querySelector("textarea").value.length===1500')
  run('screenshot',str(O/f'pixel-contact-{width}-download-failure-fixture.png'))
  run('reload');snap();run('find','role','button','click','--name','Pause scene');snap()
  assert_js('getComputedStyle(document.querySelector(".robot")).animationPlayState === "paused" && getComputedStyle(document.querySelector(".clouds")).animationPlayState === "paused"')
  run('set','media','light','reduced-motion');snap()
  assert_js('matchMedia("(prefers-reduced-motion: reduce)").matches && getComputedStyle(document.querySelector(".robot")).animationName === "none"')
  results.append({'page':'pixel-world','width':width,'cases':['empty validation','whitespace validation','email validation','1500-character draft bytes','dialog Escape/focus return','mock download failure preserves input','pause','reduced motion'],'status':'pass'})
 visit('buzzkit',width)
 for name in ['overview','workflows','segments','deliveries']:
  run('click',f'#tab-{name}');snap()
  assert_js(f'document.querySelector("#{name}").hidden===false && document.querySelector("#tab-{name}").getAttribute("aria-selected")==="true"')
  assert_js('document.body.classList.contains("paused") && getComputedStyle(document.querySelector(".notification")).animationPlayState==="paused"')
  audit(f'buzzkit-{name}-{width}','main')
  run('screenshot',str(O/f'buzzkit-{name}-{width}.png'),'--full' if width==375 else '--full')
 run('focus','#tab-deliveries');snap();run('press','ArrowRight');snap()
 assert_js('document.activeElement.id==="tab-overview" && !document.querySelector("#overview").hidden')
 run('press','End');snap();assert_js('document.activeElement.id==="tab-deliveries"')
 run('press','Home');snap();assert_js('document.activeElement.id==="tab-overview"')
 run('click','.preferences input');snap()
 assert_js('document.querySelector(".preferences [role=status]").textContent.includes("No account settings changed")')
 run('focus','.faq summary');snap();run('press','Enter');snap();assert_js('document.querySelector(".faq details").open')
 js('document.querySelector("#copy-prompt").scrollIntoView({behavior:"instant",block:"center"});true');snap();run('click','#copy-prompt');snap()
 assert_js('document.querySelector("#copy-status").textContent.length>0')
 js('document.querySelector("#pause").scrollIntoView({behavior:"instant",block:"center"});true');snap();run('click','#pause');snap()
 assert_js('!document.body.classList.contains("paused")')
 run('wait','6500');snap()
 assert_js('!document.querySelector("#workflows").hidden')
 run('set','media','light','reduced-motion');snap()
 assert_js('document.body.classList.contains("paused") && getComputedStyle(document.querySelector(".notification")).animationName==="none"')
 results.append({'page':'buzzkit','width':width,'cases':['4views and corresponding selected state','view selection pauses','Left/Right/Home/End keys','local preferences','FAQ keyboard','copy prompt feedback','autoplay advances','reduced motion'],'status':'pass'})
 visit('horizonx',width)
 run('find','role','link','click','--name','Experience');snap();assert_js('location.hash==="#about"')
 run('focus','.capabilities summary');snap();run('press','Enter');snap();assert_js('document.querySelector(".capabilities details").open')
 run('set','media','light','reduced-motion');snap()
 assert_js('getComputedStyle(document.querySelector(".ship")).animationName==="none" && getComputedStyle(document.querySelector(".cosmos")).animationName==="none"')
 results.append({'page':'horizonx','width':width,'cases':['CTA anchor','capability keyboard disclosure','reduced motion'],'status':'pass'})
(O/'interaction-results.json').write_text(json.dumps(results,indent=2))
print('PASS',len(results),'page/viewport journeys',flush=True)
