from browser import *
import re,hashlib,zipfile
out=E/'final';rows=[]
def ref(label,role='button'):
 s=snap();m=re.search(r'\b'+role+r' "'+re.escape(label)+r'"[^\n]*ref=(e\d+)',s);assert m,label;return '@'+m.group(1)
def check(name,expr):
 v=js(expr);rows.append({'case':name,'passed':bool(v),'observed':v});(out/'public.json').write_text(json.dumps(rows,indent=2));assert v,name
run('set','viewport','1440','1080');snap();run('open','https://x-web-templates.pages.dev/');snap();run('webmcp','list');run('wait','200');snap();check('gallery has21','document.querySelectorAll(".template-grid article").length===21');run('scrollintoview',ref('Preview Arto','link'));snap();run('screenshot',str(out/'public-gallery.png'))
run('click',ref('Preview Arto','link'));snap();run('webmcp','list');run('wait','200');snap();check('public assets and baseline','location.pathname==="/arto/" && document.querySelector(".mountains").naturalWidth>0 && document.querySelector("[data-amount=balance]").textContent==="$3,908.00" && document.documentElement.scrollWidth===1440');run('scroll','up','20000');snap();subprocess.run(['node','/private/tmp/xweb-arto-0910/capture.mjs',str(out/'public-arto.png')],check=True)
run('fill',ref('Search transactions','searchbox'),'Spotify');snap();run('click',ref('Details for Spotify Premium'));snap();check('public search and details','document.querySelector("#detail-dialog").open && document.querySelector("#detail-data").textContent.includes("$9.99")');run('press','Escape');snap();run('fill',ref('Search transactions','searchbox'),'');snap();run('click',ref('Add Income Log a sample income'));snap();run('fill',ref('Income description','textbox'),'Published sample entry');snap();run('fill',ref('Amount in USD','spinbutton'),'1.23');snap();run('click',ref('Add sample income'));snap();check('public local income','document.querySelector("[data-amount=balance]").textContent==="$3,909.23" && document.querySelector("#action-result").textContent.includes("sample ledger")');run('press','Escape');snap()
run('set','viewport','375','812');snap();check('public mobile no overflow','document.documentElement.scrollWidth===375');run('focus',ref('Transactions','link'));snap();run('press','Enter');snap();run('focus',ref('Transactions table, scroll horizontally on narrow screens','region'));snap();run('press','ArrowRight');snap();run('wait','150');check('mobile table keyboard scroll','document.querySelector(".table-scroll").scrollLeft>0');run('screenshot',str(out/'public-mobile-table.png'))
(out/'public-errors.txt').write_text(run('errors'));(out/'public-network.json').write_text(run('network','requests','--json'))
run('open','https://x-web-templates.pages.dev/');snap();run('webmcp','list');run('download','a[href="downloads/arto.zip"]',str(out/'public-arto.zip'));snap();assert hashlib.sha256((out/'public-arto.zip').read_bytes()).digest()==hashlib.sha256((R/'dist/downloads/arto.zip').read_bytes()).digest();rows.append({'case':'public ZIP exact bytes','passed':True});(out/'public.json').write_text(json.dumps(rows,indent=2))
extract=Path('/private/tmp/xweb-arto-0910/unzipped')
with zipfile.ZipFile(out/'public-arto.zip') as z:z.extractall(extract)
run('open',(extract/'arto/dist/index.html').as_uri());snap();run('webmcp','list');run('wait','200');snap();check('ZIP opens standalone','location.protocol==="file:" && document.querySelector(".mountains").naturalWidth>0 && document.querySelector("[data-amount=balance]").textContent==="$3,908.00"');run('click',ref('7D'));snap();check('standalone data filter','document.querySelector("[data-amount=income]").textContent==="$2,350.00"');run('fill',ref('Search transactions','searchbox'),'Spotify');snap();run('click',ref('Details for Spotify Premium'));snap();check('standalone detail interaction','document.querySelector("#detail-dialog").open');run('press','Escape');snap()
print(f'{len(rows)} public and standalone assertions passed')
