from browser import *
import re
OUT=E/'final';OUT.mkdir(exist_ok=True);rows=[]
def ref(label,role='button'):
 s=snap();m=re.search(r'\b'+role+r' "'+re.escape(label)+r'"[^\n]*ref=(e\d+)',s);assert m,(label,s[-2400:]);return '@'+m.group(1)
def click(label,role='button'):
 run('click',ref(label,role));snap()
def fill(label,value,role='textbox'):
 run('fill',ref(label,role),value);snap()
def check(name,expr):
 value=js(expr);rows.append({'case':name,'passed':bool(value),'observed':value});(OUT/'interactions.json').write_text(json.dumps(rows,indent=2));assert value,name

def screen(name):subprocess.run(['node','/private/tmp/xweb-arto-0910/capture.mjs',str(OUT/name)],check=True,capture_output=True)
for w in [1440,375]:
 visit('arto',w,'final');check(f'loaded baseline {w}','document.querySelector("[data-amount=balance]").textContent==="$3,908.00" && document.querySelectorAll("#transaction-rows tr").length===5 && document.documentElement.scrollWidth===innerWidth')
 click('7D');check(f'7day sample totals {w}','document.querySelector("[data-amount=income]").textContent==="$2,350.00" && document.querySelector("[data-amount=expense]").textContent==="$329.99" && document.querySelector("[data-amount=savings]").textContent==="$2,020.01" && document.querySelector("[data-amount=balance]").textContent==="$3,908.00"')
 click('30D');check(f'30day filter {w}','document.querySelector("[data-amount=expense]").textContent==="$1,129.99"');click('1Y')
 run('focus',ref('Hide total balance'));snap();run('press','Enter');snap();check(f'hide via keyboard {w}','document.querySelector("[data-amount=balance]").textContent==="••••••"');click('Show total balance');check(f'show restores {w}','document.querySelector("[data-amount=balance]").textContent==="$3,908.00"')
 fill('Search transactions','spotify','searchbox');check(f'known search {w}','document.querySelectorAll("#transaction-rows tr").length===1 && document.querySelector("#transaction-rows").textContent.includes("Spotify")');click('Details for Spotify Premium');check(f'details open {w}','document.querySelector("#detail-dialog").open && document.querySelector("#detail-data").textContent.includes("$9.99")');screen(f'detail-{w}.png');run('press','Escape');snap();check(f'detail focus restored {w}','document.activeElement.getAttribute("aria-label")==="Details for Spotify Premium"')
 fill('Search transactions','no-such-entry','searchbox');check(f'empty results {w}','!document.querySelector("#empty").hidden && document.querySelectorAll("#transaction-rows tr").length===0');screen(f'empty-{w}.png');fill('Search transactions','','searchbox')
 click('View all');check(f'all ledger rows {w}','document.querySelectorAll("#transaction-rows tr").length===8');click('Show recent');check(f'recent restored {w}','document.querySelectorAll("#transaction-rows tr").length===5')
 click('Income $3,898.00 ↗ +12.4%');check(f'income metric filter {w}','document.querySelector("#transactions-title").textContent==="Income transactions" && document.querySelectorAll("#transaction-rows tr").length===3');click('Income $3,898.00 ↗ +12.4%');click('Savings $1,805.00 ↗ +15.2%');check(f'savings explanation {w}','document.querySelector("#detail-title").textContent==="Savings for this period"');run('press','Escape');snap()
 for label,title in [('Notifications','You’re all caught up.'),('Profile for Alex Morgan','Alex Morgan'),('View all goals','Make room for what matters.')]:
  click(label);check(f'{label} {w}',f'document.querySelector("#detail-dialog").open && document.querySelector("#detail-title").textContent==={json.dumps(title)}');run('press','Escape');snap()
 for label in ['Budgets','Cards','Settings']:
  click(label,'link');check(f'{label} navigation {w}','document.querySelector("#detail-dialog").open');run('press','Escape');snap();check(f'{label} focus {w}',f'document.activeElement.textContent.trim()==={json.dumps(label)}')
 for label,ident in [('Transactions','transactions'),('Analytics','analytics'),('Goals','goals'),('Dashboard','overview')]:
  click(label,'link');check(f'{label} anchored navigation {w}',f'location.hash==="#{ident}" && document.activeElement.id==="{ident}"')
 run('select',ref('Chart period','combobox'),'1');snap();check(f'chart last week {w}','document.querySelector("#chart-day").max==="6" && document.querySelector(".chart-dates text").textContent==="Mar 16"');run('focus',ref('Inspect balance date','slider'));snap();before=js('document.querySelector("#chart-reading").textContent');run('press','ArrowRight');snap();after=js('document.querySelector("#chart-reading").textContent');assert before!=after;check(f'chart keyboard day changes {w}','document.querySelector("#chart-day").value==="3"');run('select',ref('Chart period','combobox'),'3');snap();screen(f'chart-{w}.png')
 click('Send Money Preview a transfer');click('Preview transfer');check(f'empty action rejected {w}','!document.querySelector("#action-name").validity.valid && document.querySelector("#action-result").textContent===""');fill('Recipient name','   ');fill('Amount in USD','25.50','spinbutton');click('Preview transfer');check(f'whitespace rejected {w}','document.querySelector("#action-name").validationMessage.includes("Enter a name")');fill('Recipient name','Sam Example');fill('Amount in USD','-1','spinbutton');click('Preview transfer');check(f'negative rejected {w}','!document.querySelector("#action-amount").validity.valid');fill('Amount in USD','25.50','spinbutton');click('Preview transfer');check(f'transfer preview truthful {w}','document.querySelector("#action-result").textContent.includes("Nothing was sent") && document.querySelector("[data-amount=balance]").textContent==="$3,908.00"');screen(f'transfer-{w}.png');run('press','Escape');snap();click('Send Money Preview a transfer');check(f'cancel preserves action {w}','document.querySelector("#action-name").value==="Sam Example" && document.querySelector("#action-submit").disabled');run('press','Escape');snap()
 click('Request Money Draft a request');fill('Requested from','Morgan Example');fill('Amount in USD','15','spinbutton');click('Preview request');check(f'request stays local {w}','document.querySelector("#action-result").textContent.includes("No request or message was sent")');run('press','Escape');snap()
 click('Add Income Log a sample income');fill('Income description','Sample illustration');fill('Amount in USD','25.50','spinbutton');click('Add sample income');check(f'income updates data {w}','document.querySelector("[data-amount=balance]").textContent==="$3,933.50" && document.querySelector("[data-amount=income]").textContent==="$3,923.50" && document.querySelector("#transaction-rows").textContent.includes("Sample illustration") && document.querySelector("#action-submit").disabled');screen(f'added-income-{w}.png');run('press','Escape');snap()
 click('Set Budget Create a sample budget');fill('Budget name','Weekend activities');fill('Amount in USD','200','spinbutton');click('Save sample budget');check(f'budget saved locally {w}','document.querySelector("#action-result").textContent.includes("$200.00")');run('press','Escape');snap();click('Budgets','link');check(f'budget review uses saved state {w}','document.querySelector("#detail-title").textContent==="Weekend activities" && document.querySelector("#detail-data").textContent.includes("$200.00")');screen(f'budget-{w}.png');run('press','Escape');snap()
 check(f'no viewport overflow {w}','document.documentElement.scrollWidth===innerWidth');a=run('a11y','--selector','.workspace','--json');(OUT/f'axe-{w}.json').write_text(a);print({'width':w,'axe':json.loads(a)['data']['violations']},flush=True);(OUT/f'errors-{w}.txt').write_text(run('errors'));(OUT/f'network-{w}.json').write_text(run('network','requests','--json'));print(f'PASS core flow {w}',flush=True)
print(f'{len(rows)} assertions passed')
