from browser import *
import re,hashlib
OUT=E/'final';results=[]
def key(label,role='button'):
 s=snap();m=re.search(r'\b'+role+r' "'+re.escape(label)+r'"[^\n]*ref=(e\d+)',s);assert m,(label,s[:600]);run('focus','@'+m.group(1));snap();run('press','Enter');snap()
def check(name,expr):
 d=js(expr);results.append({'case':name,'passed':bool(d),'observed':d});(OUT/'public.json').write_text(json.dumps(results,indent=2));assert d,name
run('set','viewport','1440','1000');snap();run('open','https://x-web-templates.pages.dev/');snap();run('webmcp','list');run('wait','--fn','[...document.images].every(i=>i.complete&&i.naturalWidth>0)');snap();js('document.querySelector("#lindy-cos-root")?.style.setProperty("display","none")');check('public gallery 18','document.querySelectorAll("article").length===18 && document.querySelectorAll("article")[17].textContent.includes("Verto") && document.documentElement.scrollWidth===innerWidth');run('screenshot',str(OUT/'gallery-18-public.png'),'--full')
s=snap();matches=re.findall(r'link "Download ZIP ↓"[^\n]*ref=(e\d+)',s);assert len(matches)==18;dest=Path('/private/tmp/xweb-alex-0910/public-verto.zip');run('download','@'+matches[-1],str(dest));snap();assert hashlib.sha256(dest.read_bytes()).digest()==hashlib.sha256((R/'dist/downloads/verto.zip').read_bytes()).digest();results.append({'case':'public actual Verto ZIP download','passed':True,'bytes':dest.stat().st_size,'sha256':hashlib.sha256(dest.read_bytes()).hexdigest()});(OUT/'public.json').write_text(json.dumps(results,indent=2))
key('Preview Verto','link');run('webmcp','list');subprocess.run(['node','/private/tmp/xweb-alex-0910/reload.mjs'],check=True);snap();run('wait','--fn','document.querySelector("#scene-video").readyState>=2');snap();js('document.querySelector("#lindy-cos-root")?.style.setProperty("display","none")');check('public Verto route','location.pathname==="/verto/" && document.querySelector("h1").textContent.includes("ambitious founders")');run('screenshot',str(OUT/'verto-public-1440.png'))
run('scroll','down','1800');snap();run('wait','450');check('public scroll video seeks','document.querySelector("#scene-video").currentTime>.5 && document.querySelector("#scene-video").seekable.end(0)>5');key('UI/UX Design [ 02 ]');check('public services','document.querySelectorAll("[data-service]")[1].getAttribute("aria-pressed")==="true"');key('Explore Sonnet Print Poster');check('public project details','document.querySelector("#project-dialog").open');run('press','Escape');snap();check('public close project','!document.querySelector("#project-dialog").open')
run('set','viewport','375','812');snap();key('Let’s Talk')
for label,value in [('Project name','Public release check'),('Your brief','A local project brief from the deployed Verto template.')]:
 s=snap();m=re.search('textbox "'+label+'"[^\n]*ref=(e\\d+)',s);assert m;run('fill','@'+m.group(1),value);snap()
s=snap();m=re.search('button "Download my brief ↓"[^\n]*ref=(e\\d+)',s);dest=Path('/private/tmp/xweb-alex-0910/public-brief.txt');run('download','@'+m.group(1),str(dest));snap();assert 'Public release check' in dest.read_text();check('public mobile export feedback','document.querySelector("#brief-status").textContent.includes("Download requested") && document.documentElement.scrollWidth===innerWidth');run('screenshot',str(OUT/'verto-public-brief-375.png'));run('press','Escape');snap();js('window.scrollTo({top:0,behavior:"instant"})');snap();run('wait','300');run('screenshot',str(OUT/'verto-public-375.png'))
print(f'{len(results)} public checks passed',flush=True)
